language: php
php:
- 7.3
- 7.4

jobs:
    include:
        - php: 7.2
          before_script:
              - sed -i 's/9.0/8.0/g' composer.json
              - composer install

before_script:
- composer install

script:
- ./vendor/bin/phpunit
- ./vendor/bin/infection --min-msi=75 --min-covered-msi=75
